version: "3.9"
services:
  web:
    build: .
    command: gunicorn smartDelivery.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: smartdelivery_db
      POSTGRES_USER: databaseuser
      POSTGRES_PASSWORD: iamgroot
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
