# Generated by Django 5.1.7 on 2025-03-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_rename_cancelled_order_deliverypartner_cancelled_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
